### ISSUE TITLE
get_activities_export_job_status => TypeError: 'Response' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by joefusaro** [jepcastelein/marketo-rest-python#32] opened 2018-09-18 21:46 UTC
I've followed the methods for creating a batch job, which appears to be successful. 

```
>>> mc = MarketoClient(munchkin_id, client_id, client_secret)
>>> new_export_job_details = mc.execute(
...     method='create_activities_export_job',
...     fields=[
...         'leadId', 'primaryAttributeValue', 'activityDate', 'attributes',
...         'marketoGUID', 'activityTypeId'
...         ],
...     filters={'createdAt': {'endAt': '2018-08-31', 'startAt': '2018-08-01'}}
...     )
>>> new_export_job_details
[{u'status': u'Created', u'exportId': u'aa89d3ee-98bb-4122-b38b-667cf4e09843', u'createdAt': u'2018-09-18T19:21:31Z', u'format': u'CSV'}]
```
However, I'm getting an error trying to retrieve the job status:

```
>>> export_job_status = mc.execute(method='get_activities_export_job_status', job_id='aa89d3ee-98bb-4122-b38b-667cf4e09843')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/joefusaro/text_analysis/venv/lib/python2.7/site-packages/marketorestpython/client.py", line 256, in execute
    result = method_map[method](*args, **kargs)
  File "/Users/joefusaro/text_analysis/venv/lib/python2.7/site-packages/marketorestpython/client.py", line 4963, in get_activities_export_job_status
    return self._export_job_state_machine('activities', 'status', *args, **kargs)
  File "/Users/joefusaro/text_analysis/venv/lib/python2.7/site-packages/marketorestpython/client.py", line 4949, in _export_job_state_machine
    if not result['success']:
TypeError: 'Response' object has no attribute '__getitem__'
```

Am I doing something wrong, or is this something that needs to be fixed? If I can help, I'd be happy to dig in...

**Comment by jepcastelein** [comment] 2018-10-24 00:09
duplicate of #28 . Now fixed in 0.3.16

**Closed by jepcastelein** 2018-10-24 00:09 UTC
